version: '3.8'

services:
  ubuntu2004_media:
    image: falcon-pub
    container_name: ubuntu2004_media
    runtime: nvidia
    shm_size: '1024m'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/media0:/dev/media0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/share:/root/share
    stdin_open: true # -i flag
    tty: true        # -t flag
    command: python3 main.py --tag_id 15

# sudo docker run --runtime=nvidia --shm-size=1024m -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=all --net=host --env="DISPLAY" --device=/dev/snd:/dev/snd --device=/dev/video0:/dev/video0 --device=/dev/video1:/dev/video1 --device=/dev/media0:/dev/media0 -i -t -v /etc/localtime:/etc/localtime:ro -v /home/docker/share:/root/share --name=ubuntu2004_media test-cam /bin/bash