FROM docker.io/pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime

RUN apt-get update

RUN apt-get install v4l-utils -y

RUN apt-get install -y libgl1-mesa-glx

RUN pip install opencv-python

RUN pip install nats-py

RUN apt-get install libglib2.0-0 -y

RUN pip install torchvision==0.17.0

RUN pip install torchaudio==2.2.0

RUN pip install botocore==1.34.54

RUN pip install xformers==0.0.24

RUN pip install h5py>=3.10.0 && pip install black && pip install blosc2 && pip install fonttools && pip install kiwisolver && pip install matplotlib && pip install pandas && pip install scipy && pip install tables

COPY . .

# 최초 이미지 빌드