FROM pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime

RUN apt-get update

RUN apt-get install v4l-utils -y

RUN apt-get install -y libgl1-mesa-glx

RUN pip install opencv-python

RUN pip install nats-py

RUN apt-get install libglib2.0-0 -y

RUN pip install torchvision==0.17.0

RUN pip install torchaudio==2.2.0

COPY . .